# name: Deploy

# on:
#   push:
#     branches:
#       - master 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up SSH key
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#       run: |
#         echo "$SSH_PRIVATE_KEY" > keyfile
#         chmod 600 keyfile

#     - name: Add EC2 Host to known_hosts
#       run: |
#         mkdir -p ~/.ssh
#         ssh-keyscan ec2-16-171-13-91.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

#     - name: Deploy to EC2
#       run: |
#         ssh -t -i keyfile ubuntu@ec2-16-171-13-91.eu-north-1.compute.amazonaws.com "bash ~/deploy.sh"




name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Up SSH Key
      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ssh-keyscan -H ec2-54-146-244-40.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      # Step 3: Run Deployment Script on EC2
      - name: Run Deployment Script
        run: |
          ssh -i ~/.ssh/github_deploy_key ubuntu@ec2-54-146-244-40.compute-1.amazonaws.com "sudo bash ~/deploy.sh"
        shell: bash

# name: Deploy

# on:
#   push:
#     branches:
#       - master 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup SSH Agent
#       uses: webfactory/ssh-agent@v0.5.4
#       with:
#         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#     - name: Add EC2 Host to known_hosts
#       run: |
#         ssh-keyscan -H ec2-54-146-244-40.compute-1.amazonaws.com >> ~/.ssh/known_hosts

#     - name: Deploy to EC2
#       run: |
#         ssh ubuntu@ec2-54-146-244-40.compute-1.amazonaws.com "bash ~/deploy.sh"
